CREATE TABLE adventure_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    CONSTRAINT ck_adventure_books_difficulty
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD'))
);

CREATE TABLE book_categories (
    book_id BIGINT NOT NULL,
    category VARCHAR(100) NOT NULL,
    PRIMARY KEY (book_id, category),
    CONSTRAINT fk_book_categories_book
        FOREIGN KEY (book_id) REFERENCES adventure_books (id) ON DELETE CASCADE,
    CONSTRAINT ck_book_categories_category_not_blank
        CHECK (TRIM(category) <> '')
);

CREATE INDEX idx_book_categories_category
    ON book_categories (category);

CREATE TABLE sections (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
                          section_number BIGINT NOT NULL,
    text TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    CONSTRAINT fk_sections_book
        FOREIGN KEY (book_id) REFERENCES adventure_books (id) ON DELETE CASCADE,
                          CONSTRAINT uq_sections_book_section_number UNIQUE (book_id, section_number),
    CONSTRAINT ck_sections_type
        CHECK (type IN ('BEGIN', 'NODE', 'END'))
);

CREATE TABLE options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    goto_id BIGINT NOT NULL,
    consequence_type VARCHAR(20),
    consequence_value INTEGER,
    consequence_text TEXT,
    CONSTRAINT fk_options_section
        FOREIGN KEY (section_id) REFERENCES sections (id) ON DELETE CASCADE,
    CONSTRAINT ck_options_consequence_type
        CHECK (consequence_type IS NULL OR consequence_type IN ('LOSE_HEALTH', 'GAIN_HEALTH')),
    CONSTRAINT ck_options_consequence_value
        CHECK (consequence_value IS NULL OR consequence_value > 0),
    CONSTRAINT ck_options_consequence_complete
        CHECK (
            (consequence_type IS NULL AND consequence_value IS NULL AND consequence_text IS NULL)
            OR (consequence_type IS NOT NULL AND consequence_value IS NOT NULL AND consequence_text IS NOT NULL)
        )
);

CREATE INDEX idx_options_source
    ON options (section_id);

CREATE INDEX idx_options_destination
    ON options (goto_id);
