CREATE TABLE reading_sessions
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id                BIGINT                   NOT NULL,
    current_section_number BIGINT                   NOT NULL,
    health                 INTEGER                  NOT NULL,
    status                 VARCHAR(20)              NOT NULL,
    started_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at               TIMESTAMP WITH TIME ZONE,
    version                BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT fk_reading_sessions_book
        FOREIGN KEY (book_id) REFERENCES adventure_books (id) ON DELETE CASCADE,
    CONSTRAINT fk_reading_sessions_current_section
        FOREIGN KEY (book_id, current_section_number)
            REFERENCES sections (book_id, section_number),
    CONSTRAINT ck_reading_sessions_current_section_number
        CHECK (current_section_number > 0),
    CONSTRAINT ck_reading_sessions_health
        CHECK (health BETWEEN 0 AND 10),
    CONSTRAINT ck_reading_sessions_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'DEAD', 'STUCK'))
);

CREATE INDEX idx_reading_sessions_book
    ON reading_sessions (book_id);
